-- 1. Add real OTP verification columns to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_code VARCHAR(6) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_code_expires_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

ALTER TABLE users ALTER COLUMN phone DROP NOT NULL;

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
